import Link from "next/link";
import { Building2, ChevronLeft, ChevronRight, Filter, Globe2, Plus, Search } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { getAccessContext } from "@/lib/role-access";

const countryNames: Record<string, string> = { SK: "Slovakia", CZ: "Czechia", GB: "United Kingdom" };
export default async function CompaniesPage({ searchParams }: { searchParams: Promise<{ q?: string; country?: string; page?: string }> }) {
  const { q = "", country = "", page = "1" } = await searchParams; const current = Math.max(1, Number(page) || 1); const take = 10;
  const { workspace, user, founder } = await getAccessContext();
  const where = { workspaceId: workspace.id, deletedAt: null, ...(!founder ? { ownerId: user.id } : {}), ...(country ? { country } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { domain: { contains: q, mode: "insensitive" as const } }, { city: { contains: q, mode: "insensitive" as const } }] } : {}) };
  const [companies, total] = await Promise.all([prisma.company.findMany({ where, include: { _count: { select: { contacts: true, opportunities: true, activities: true } }, owner: { select: { name: true } } }, orderBy: { updatedAt: "desc" }, skip: (current - 1) * take, take }), prisma.company.count({ where })]);
  const pages = Math.max(1, Math.ceil(total / take));
  return <><div className="list-heading"><div><p className="eyebrow">CRM · RELATIONSHIPS</p><h1>Companies</h1><p>{total} organisations in the Thrive Dev workspace</p></div><Link className="primary-link" href="/companies/new"><Plus size={16} /> Add company</Link></div><div className="list-toolbar"><form><div className="table-search"><Search size={15} /><input name="q" defaultValue={q} placeholder="Search name, domain or city" /></div><select name="country" defaultValue={country}><option value="">All countries</option><option value="SK">Slovakia</option><option value="CZ">Czechia</option><option value="GB">United Kingdom</option></select><button><Filter size={14} /> Apply filters</button></form><span>{total} results</span></div><section className="data-card">{companies.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Company</th><th>Location</th><th>Industry</th><th>Relationships</th><th>Owner</th><th>Lifecycle</th><th /></tr></thead><tbody>{companies.map(company => <tr key={company.id}><td><Link href={`/companies/${company.id}`}><span className="company-logo">{company.name.slice(0,2).toUpperCase()}</span><span><strong>{company.name}</strong><small><Globe2 size={10} />{company.domain ?? "No domain"}</small></span></Link></td><td><strong>{company.city ?? "—"}</strong><small>{company.country ? countryNames[company.country] : "Unknown"}</small></td><td><span className="tag">{company.industry ?? "Unclassified"}</span></td><td><strong>{company._count.contacts} contacts</strong><small>{company._count.opportunities} opportunities</small></td><td>{company.owner?.name ?? "Unassigned"}</td><td><span className="status-dot"><i />{company.lifecycleStatus.toLowerCase()}</span></td><td><Link href={`/companies/${company.id}`}><ChevronRight size={16} /></Link></td></tr>)}</tbody></table></div> : <div className="empty-state"><Building2 size={28} /><h2>No matching companies</h2><p>Change the filters or add a company to the CRM.</p></div>}<footer className="table-footer"><span>Page {current} of {pages}</span><div><Link aria-disabled={current <= 1} href={`?q=${q}&country=${country}&page=${Math.max(1,current-1)}`}><ChevronLeft size={15} /></Link><Link aria-disabled={current >= pages} href={`?q=${q}&country=${country}&page=${Math.min(pages,current+1)}`}><ChevronRight size={15} /></Link></div></footer></section></>;
}
